language: ruby

sudo: required

services:
  - docker

before-install:
  - docker build -t -stuprosonic/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stuprosonic/docker-react npm run test

#deploy:
 # provider: elasticbeanstalk
  #region: "us-west-2"
  #app: "docker"
 # env: "Docker-env"
  #bucket_name: "elasticbeanstalk"
 # bucket_path: "docker"
  #on:
  #  branch: master*/